<?php

/**
 * MovieOrderItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MovieOrderItemTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MovieOrderItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MovieOrderItem');
    }
}