<?php

/**
 * MovieTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MovieTable extends Doctrine_Table
{
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Movie');
    }

    public function getDirectors()
    {
        $q = $this
            ->createQuery('m')
            ->select('m.director')
            ->distinct()
            ->orderBy('m.director ASC')
        ;

        $directors = array();
        foreach ($q->execute(array(), Doctrine_Core::HYDRATE_ARRAY) as $row) {
            $directors[ $row['director'] ] = $row['director'];
        }

        return $directors;
    }

    public function getAll()
    {
        return $this->getStandardMovieQuery()->execute();
    }

    public function getByCategory($type)
    {
        $q = $this
            ->getStandardMovieQuery()
            ->where('m.type = ?', $type)
        ;

        return $q->execute();
    }

    public function getStandardMovieQuery()
    {
        return $this
            ->createQuery('m')
            ->orderBy('m.shot_year DESC')
        ;
    }

    static public function getMovieSupports()
    {
        return array(
            'dvd'     => 'DVD',
            'vhs'     => 'VHS',
            'avi'     => 'AVI',
            'blueray' => 'Blue Ray',
        );
    }

    static public function getMovieTypes()
    {
        return array(
            'action'      => 'Action',
            'aventure'    => 'Aventure',
            'cartoon'     => 'Cartoon',
            'comedy'      => 'Comedy',
            'documentary' => 'Documentary',
            'horror'      => 'Horror',
            'romance'     => 'Romantic',
            'scifi'       => 'Science Fiction',
            'thriller'    => 'Thriller',
        );
    }
}