<?php

/**
 * MovieOrder
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class MovieOrder extends BaseMovieOrder
{
    const VAT = 0.196;

    private $movies;

    private $cart;

    public function setMovies($movies)
    {
        $this->movies = $movies;
    }

    public function setCart(array $cart)
    {
        $this->cart = $cart;
    }

    public function setReference($reference)
    {
        $this->_set('reference', substr($reference, 0, 10));
    }

    public function updateAmount()
    {
        $amount = 0;
        $vat    = 0;
        $total  = 0;

        foreach ($this->getItems() as $item) {
            $amount += $item->getUnitPrice() * $item->getQuantity();
        }

        $vat = $amount * self::VAT;

        $this->setAmount($amount);
        $this->setVat($vat);
        $this->setTotal($amount + $vat);
    }

    public function setAmount($amount)
    {
        $this->_set('amount', round($amount, 2));
    }

    public function setVat($vat)
    {
        $this->_set('vat', round($vat, 2));
    }

    public function setTotal($total)
    {
        $this->_set('total', round($total, 2));
    }

    public function init()
    {
        foreach ($this->cart as $id => $quantity) {

            $movie = $this->getMovie($id);

            $item = new MovieOrderItem();
            $item->setFilm($movie);
            $item->setQuantity($quantity);

            $this->Items->add($item);
        }
    }

    private function getMovie($id)
    {
        $theMovie = null;
        foreach ($this->movies as $movie) {
            if ($id == $movie->getId()) {
                $theMovie = $movie;
                break;
            }
        }

        return $theMovie;
    }
}
