<?php

/**
 * MovieOrderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MovieOrderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MovieOrderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MovieOrder');
    }

    public function newOrder(array $cart)
    {
        $movies = Doctrine_Query::create()
            ->from('Movie m')
            ->whereIn('m.id', array_keys($cart))
            ->execute()
        ;

        $order = new MovieOrder();
        $order->setMovies($movies);
        $order->setCart($cart);
        $order->init();

        return $order;
    }
}