<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version4 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('movie_order', 'address', 'clob', '', array(
             ));
        $this->addColumn('movie_order', 'zip_code', 'string', '20', array(
             ));
        $this->addColumn('movie_order', 'country', 'string', '100', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('movie_order', 'address');
        $this->removeColumn('movie_order', 'zip_code');
        $this->removeColumn('movie_order', 'country');
    }
}