<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('movie_order', 'movie_order_user_id_sf_guard_user_id', array(
             'name' => 'movie_order_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('movie_order_item', 'movie_order_item_order_id_movie_order_id', array(
             'name' => 'movie_order_item_order_id_movie_order_id',
             'local' => 'order_id',
             'foreign' => 'id',
             'foreignTable' => 'movie_order',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('movie_order_item', 'movie_order_item_movie_id_movie_id', array(
             'name' => 'movie_order_item_movie_id_movie_id',
             'local' => 'movie_id',
             'foreign' => 'id',
             'foreignTable' => 'movie',
             ));
        $this->addIndex('movie_order', 'movie_order_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->addIndex('movie_order_item', 'movie_order_item_order_id', array(
             'fields' => 
             array(
              0 => 'order_id',
             ),
             ));
        $this->addIndex('movie_order_item', 'movie_order_item_movie_id', array(
             'fields' => 
             array(
              0 => 'movie_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('movie_order', 'movie_order_user_id_sf_guard_user_id');
        $this->dropForeignKey('movie_order_item', 'movie_order_item_order_id_movie_order_id');
        $this->dropForeignKey('movie_order_item', 'movie_order_item_movie_id_movie_id');
        $this->removeIndex('movie_order', 'movie_order_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->removeIndex('movie_order_item', 'movie_order_item_order_id', array(
             'fields' => 
             array(
              0 => 'order_id',
             ),
             ));
        $this->removeIndex('movie_order_item', 'movie_order_item_movie_id', array(
             'fields' => 
             array(
              0 => 'movie_id',
             ),
             ));
    }
}